[package]
name = "chess-gui"
version = "0.1.0"
authors = ["arian"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chess = { path = "../inda20plusplus/ahanifi-chess/chess" }
ggez = "0.5"
